[[main]]
none = "none"

[[main]]
  name = "Author"
  pre = "author"
  pageRef = "author-bio"
  weight = 10

[[main]]
  name = "Contact"
  pre = "envelope1"
  pageRef = "contact-us"
  weight = 20

[[main]]
  name = "Portfolio"
  pre = "grid"
  weight = 30

[[main]]
  parent = "Portfolio"
  identifier = "in-stores-now"
  pageRef = "portfolio"
  pre = "purchase"
  weight = 31
  name = "&nbsp;In&nbsp;Stores&nbsp;Now"

[[main]]
  parent = "Portfolio"
  identifier = "coming-soon"
  pageRef = "portfolio/coming-soon"
  pre = "announcement-icon"
  weight = 32
  name = "&nbsp;Coming&nbsp;Soon"

[[main]]
  name = "Policy&nbsp;Center"
  pre = "information"
  pageRef = "policy-center"
  weight = 40

[[main]]
  name = "External&nbsp;Links"
  pre = "link"
  weight = 50

[[main]]
  parent = "External&nbsp;Links"
  identifier = "target"
  name = "Target"
  pre = "bullseye"
  url = "https://www.target.com/s?searchTerm=himani+malhotra+books&tref=typeahead%7Cterm%7Chimani+malhotra+books%7C%7C%7Chistory"
  weight = 60

[[main]]
  parent = "External&nbsp;Links"
  identifier = "amazon"
  name = "Amazon"
  pre = "amazon"
  url = "https://www.amazon.com/s?k=himani+malhotra+%2B+jason+pacliwan+%2B+witty+pen&crid=1QEVQUA2JPCIA&sprefix=himani+malhotra+%2B+jason+pacliwan+%2B+witty+pen%2Caps%2C128&ref=nb_sb_noss"
  weight = 65

[[main]]
  parent = "External&nbsp;Links"
  identifier = "walmart"
  name = "Walmart"
  pre = "walmart1"
  url = "https://www.walmart.com/search?q=Himani+Malhotra%3B+Jason+Pacliwan&facet=brand%3AHimani+Malhotra%3B+Jason+Pacliwan%7C%7Cbrand%3AHimani+Malhotra%7C%7Cbrand%3AWitty+Pen+Media%2C+LLC"
  weight = 70

[[main]]
  parent = "External&nbsp;Links"
  identifier = "Youtube"
  name ="Youtube"
  pre = "youtube"
  url = "https://www.youtube.com/channel/UC0M9TsDeoNSSru-J-CYiH2A"
  weight = 75

[[main]]
  parent = "External&nbsp;Links"
  identifier = "twitter"
  name = "Twitter(X)"
  pre = "x-twitter"
  url = "https://twitter.com/momoandslowmo"
  weight = 80

[[main]]
  parent = "External&nbsp;Links"
  identifier = "instagram"
  name = "Instagram"
  pre = "threads"
  url = "https://www.instagram.com/momoandslowmo?utm_source=qr&igsh=MTM4NzE4Yjh2N3I0eQ=="
  weight = 90

[[footer]]
none = "none"
showScrollToTop = true